### ISSUE TITLE
Add API

### ISSUE THREAD

**Issue by AlexOgn** [bahtyr/champsdb#38]
Not an issue, more like a suggestion. I think the site is practical and easy to use and understand but an API would really boost the _cool_ stat to the website.

**Comment by bahtyr** [comment]
Thanks you for your suggestion, happy to see that there is an interest for the project.

I think I would like to wait a bit more for the project to get more mature before providing an API. Its not so clear to me how much data will be stored or how they will be stored, and I am planning to migrate the data to an actual DB as well, so theres alot more work to do.

For now instead of an API I guess one could just load the JSON files from their git raw url and access.

**Comment by AlexOgn** [comment]
So um... I made an API... message me if you have interest, it uses python, flask and your JSON file
